window.PROVIDERS = [
  {
    id: "goto-car2go",
    name: "GoTo / CAR2GO",
    hebrewName: "גוטו / קאר2גו",
    vehicleTypes: ["standard"],
    hasEV: false,
    description: "App-based carsharing in major Israeli cities, with cars, family vehicles and vans available for planned short-term use.",
    descriptionHe: "שירות שיתוף רכבים מבוסס אפליקציה במספר ערים מרכזיות בישראל, עם רכבים פרטיים, רכבים משפחתיים ומסחריות לשימוש קצר ומתוכנן.",
    category: "round_trip_carsharing",
    serviceTypeLabel: "Round-trip carsharing",
    serviceTypeLabelHe: "שיתוף רכב הלוך-חזור",
    returnModel: "Dedicated parking / return to designated location",
    returnModelHe: "חניה ייעודית / החזרה למיקום מוגדר",
    pricingModels: ["hourly", "daily", "membership-based"],
    pricingModelsHe: ["לפי שעה", "יומי", "מבוסס מנוי"],
    cities: ["Tel Aviv", "Jerusalem", "Haifa", "Netanya", "Herzliya", "Petah Tikva", "Modiin", "Ramat Gan", "Giv'atayim", "Kfar Saba", "Bat Yam", "Holon", "Ra'anana", "Hod Hasharon"],
    cityNamesHe: ["תל אביב", "ירושלים", "חיפה", "נתניה", "הרצליה", "פתח תקווה", "מודיעין", "רמת גן", "גבעתיים", "כפר סבא", "בת ים", "חולון", "רעננה", "הוד השרון"],
    appBased: true,
    touristFriendly: "unknown",
    bestFor: ["planned errands", "city trips", "people without a private car", "vans / moving"],
    bestForHe: ["סידורים מתוכננים", "נסיעות עירוניות", "אנשים ללא רכב פרטי", "מסחריות / מעבר דירה"],
    website: "https://gotoglobal.com/en/goto-car-sharing/",
    logoUrl: "https://www.google.com/s2/favicons?sz=96&domain=gotoglobal.com",
    confidence: "high",
    lastChecked: "June 2026",
    lastCheckedHe: "יוני 2026",
    dataStatus: "Provider page checked; city-level terms need verification",
    dataStatusHe: "עמוד הספק נבדק; תנאים ברמת עיר דורשים אימות",
    sourceLabel: "GoTo official site / app listings"
  },
  {
    id: "autotel",
    name: "AutoTel",
    hebrewName: "אוטותל",
    vehicleTypes: ["electric", "hybrid"],
    hasEV: true,
    description: "Tel Aviv-Yafo carsharing service for short urban trips, with A-to-B returns inside the service area.",
    descriptionHe: "שירות שיתוף רכב בתל אביב-יפו לנסיעות עירוניות קצרות, עם החזרה מנקודה לנקודה בתוך אזור השירות.",
    category: "free_floating_area_carsharing",
    serviceTypeLabel: "Free-floating / area-based carsharing",
    serviceTypeLabelHe: "שיתוף רכב אזורי / חופשי",
    returnModel: "A-to-B within Tel Aviv-Yafo service area",
    returnModelHe: "מנקודה לנקודה בתוך אזור השירות בתל אביב-יפו",
    pricingModels: ["per minute", "short urban trips"],
    pricingModelsHe: ["לפי דקה", "נסיעות עירוניות קצרות"],
    cities: ["Tel Aviv-Yafo"],
    cityNamesHe: ["תל אביב-יפו"],
    appBased: true,
    touristFriendly: "unknown",
    bestFor: ["quick city trips", "Tel Aviv users", "short urban errands"],
    bestForHe: ["נסיעות עירוניות מהירות", "משתמשים בתל אביב", "סידורים עירוניים קצרים"],
    website: "https://autotel.co.il/en/",
    logoUrl: "https://www.google.com/s2/favicons?sz=96&domain=autotel.co.il",
    confidence: "high",
    lastChecked: "June 2026",
    lastCheckedHe: "יוני 2026",
    dataStatus: "Provider page checked; eligibility and tourist use need verification",
    dataStatusHe: "עמוד הספק נבדק; זכאות ושימוש לתיירים דורשים אימות",
    sourceLabel: "AutoTel official/app listings"
  },
  {
    id: "citycar",
    name: "CityCar",
    hebrewName: "סיטי קאר",
    vehicleTypes: ["standard"],
    hasEV: false,
    description: "Large Israeli carsharing provider with broad geographic coverage. Relevant for users outside the largest urban core as well as families and planned trips.",
    descriptionHe: "ספק ישראלי גדול של שיתוף רכבים עם פריסה גיאוגרפית רחבה. רלוונטי גם מחוץ למרכזים העירוניים הגדולים, למשפחות ולנסיעות מתוכננות.",
    category: "round_trip_carsharing",
    serviceTypeLabel: "Round-trip carsharing",
    serviceTypeLabelHe: "שיתוף רכב הלוך-חזור",
    returnModel: "Likely same-station return; verify by location",
    returnModelHe: "כנראה החזרה לאותה תחנה; יש לבדוק לפי מיקום",
    pricingModels: ["hourly", "daily", "subscription required"],
    pricingModelsHe: ["לפי שעה", "יומי", "ייתכן שנדרש מנוי"],
    cities: ["Multiple cities in Israel", "50+ cities"],
    cityNamesHe: ["מספר ערים בישראל", "יותר מ-50 ערים"],
    appBased: true,
    touristFriendly: "unknown",
    bestFor: ["planned trips", "families", "users outside Tel Aviv"],
    bestForHe: ["נסיעות מתוכננות", "משפחות", "משתמשים מחוץ לתל אביב"],
    website: "https://www.citycar.co.il/",
    logoUrl: "https://www.google.com/s2/favicons?sz=96&domain=citycar.co.il",
    confidence: "medium",
    lastChecked: "June 2026",
    lastCheckedHe: "יוני 2026",
    dataStatus: "General provider presence checked; city-level list should be extracted",
    dataStatusHe: "נוכחות הספק נבדקה באופן כללי; יש לחלץ רשימת ערים מדויקת",
    sourceLabel: "CityCar official site / Google Play"
  },
  {
    id: "share-israel",
    name: "Share - Israel Car Sharing",
    hebrewName: "שלמה Share",
    vehicleTypes: ["standard"],
    hasEV: false,
    description: "Self-service car access from Shlomo Group, positioned between carsharing and short-term rental.",
    descriptionHe: "גישה עצמית לרכב מקבוצת שלמה, במיקום ביניים בין שיתוף רכב להשכרה קצרה.",
    category: "self_service_short_term_access",
    serviceTypeLabel: "Self-service short-term app rental",
    serviceTypeLabelHe: "השכרה קצרה בשירות עצמי דרך אפליקציה",
    returnModel: "Designated location / verify in app",
    returnModelHe: "מיקום מוגדר / יש לבדוק באפליקציה",
    pricingModels: ["hourly", "per kilometer", "self-service rental"],
    pricingModelsHe: ["לפי שעה", "לפי קילומטר", "השכרה בשירות עצמי"],
    cities: ["All over the country", "Needs city-level verification"],
    cityNamesHe: ["ברחבי הארץ", "דורש אימות ברמת עיר"],
    appBased: true,
    touristFriendly: "unknown",
    bestFor: ["planned trips", "users who prefer no branch paperwork", "hourly rental"],
    bestForHe: ["נסיעות מתוכננות", "משתמשים שמעדיפים פחות התעסקות בסניף", "השכרה לפי שעה"],
    website: "https://en.shlomo.co.il/share-israel/share-israel-faq",
    logoUrl: "https://www.google.com/s2/favicons?sz=96&domain=shlomo.co.il",
    confidence: "medium",
    lastChecked: "June 2026",
    lastCheckedHe: "יוני 2026",
    dataStatus: "Included as borderline carsharing / short-term access; service-area detail needed",
    dataStatusHe: "נכלל כשירות גבולי בין שיתוף רכב להשכרה קצרה; דרוש פירוט אזורי שירות",
    sourceLabel: "Shlomo FAQ / app listings"
  },
  {
    id: "mycar",
    name: "My Car",
    hebrewName: "מיי קאר",
    vehicleTypes: ["standard"],
    hasEV: false,
    description: "Station-based shared car service with hourly booking and availability in several Israeli cities and communities.",
    descriptionHe: "שירות שיתוף רכבים מבוסס תחנות עם הזמנה לפי שעה וזמינות במספר ערים וקהילות בישראל.",
    category: "round_trip_carsharing",
    serviceTypeLabel: "Round-trip carsharing",
    serviceTypeLabelHe: "שיתוף רכב הלוך-חזור",
    returnModel: "Return to origin station",
    returnModelHe: "החזרה לתחנת המוצא",
    pricingModels: ["hourly", "daily", "per kilometer"],
    pricingModelsHe: ["לפי שעה", "יומי", "לפי קילומטר"],
    cities: ["Jerusalem", "Bnei Brak", "Elad", "Beit Shemesh", "Beitar Illit", "Ashdod", "Modiin Illit", "Meron"],
    cityNamesHe: ["ירושלים", "בני ברק", "אלעד", "בית שמש", "ביתר עילית", "אשדוד", "מודיעין עילית", "מירון"],
    appBased: true,
    touristFriendly: "unknown",
    bestFor: ["planned errands", "families", "station-based users", "religious communities"],
    bestForHe: ["סידורים מתוכננים", "משפחות", "משתמשים שמעדיפים תחנות", "קהילות דתיות"],
    website: "https://www.mycar-israel.com/",
    logoUrl: "https://www.google.com/s2/favicons?sz=96&domain=mycar-israel.com",
    confidence: "high",
    lastChecked: "June 2026",
    lastCheckedHe: "יוני 2026",
    dataStatus: "Provider page checked; current city/station coverage should be verified",
    dataStatusHe: "עמוד הספק נבדק; יש לאמת כיסוי עדכני של ערים ותחנות",
    sourceLabel: "My Car official site / app listing"
  },
  {
    id: "toyota-share",
    name: "Toyota SHARE",
    hebrewName: "טויוטה SHARE",
    vehicleTypes: ["standard", "hybrid"],
    hasEV: false,
    description: "Toyota Israel's app-based short-term car access service. It is closer to short-term rental than classic urban carsharing, but useful for comparison.",
    descriptionHe: "שירות גישה קצרה לרכב מבית טויוטה ישראל דרך אפליקציה. הוא קרוב יותר להשכרה קצרה מאשר לשיתוף רכב עירוני קלאסי, אך שימושי להשוואה.",
    category: "brand_short_term_access",
    serviceTypeLabel: "Brand-based short-term access",
    serviceTypeLabelHe: "גישה קצרה לרכב של מותג",
    returnModel: "Toyota service-center / network based",
    returnModelHe: "מבוסס מרכזי שירות / רשת טויוטה",
    pricingModels: ["half-day", "daily", "monthly"],
    pricingModelsHe: ["חצי יום", "יומי", "חודשי"],
    cities: ["Tel Aviv-Yafo", "Haifa", "Ra'anana", "Netanya", "Rishon LeZion", "Kfar Saba", "Bnei Brak", "Ramla", "Bat Hefer", "Savyon", "Petah Tikva", "Ruppin College", "Tel Aviv University", "Afula", "Karmiel", "Tiberias", "Beer Sheva", "Jerusalem", "Harish", "Even Yehuda"],
    cityNamesHe: ["תל אביב-יפו", "חיפה", "רעננה", "נתניה", "ראשון לציון", "כפר סבא", "בני ברק", "רמלה", "בת חפר", "סביון", "פתח תקווה", "מכללת רופין", "אוניברסיטת תל אביב", "עפולה", "כרמיאל", "טבריה", "באר שבע", "ירושלים", "חריש", "אבן יהודה"],
    appBased: true,
    touristFriendly: "unknown",
    bestFor: ["planned trips", "half-day rental", "longer errands", "Toyota users"],
    bestForHe: ["נסיעות מתוכננות", "השכרה לחצי יום", "סידורים ארוכים יותר", "משתמשי טויוטה"],
    website: "https://www.toyota.co.il/discover-toyota/toyota-share",
    logoUrl: "https://www.google.com/s2/favicons?sz=96&domain=toyota.co.il",
    confidence: "high",
    lastChecked: "June 2026",
    lastCheckedHe: "יוני 2026",
    dataStatus: "Included as borderline short-term access; not classic carsharing",
    dataStatusHe: "נכלל כשירות גבולי לגישה קצרה לרכב; לא שיתוף רכב קלאסי",
    notes: "Borderline category: more short-term rental / subscription access than classic urban carsharing.",
    sourceLabel: "Toyota Israel official site"
  }
];

window.CATEGORY_LABELS = {
  en: {
    round_trip_carsharing: "Round-trip carsharing",
    free_floating_area_carsharing: "Free-floating / area-based",
    self_service_short_term_access: "Self-service short-term app rental",
    brand_short_term_access: "Brand-based short-term access",
    peer_to_peer_carsharing: "Peer-to-peer carsharing",
    corporate_campus_sharing: "Corporate / campus sharing"
  },
  he: {
    round_trip_carsharing: "שיתוף רכב הלוך-חזור",
    free_floating_area_carsharing: "שיתוף רכב אזורי / חופשי",
    self_service_short_term_access: "השכרה קצרה בשירות עצמי דרך אפליקציה",
    brand_short_term_access: "גישה קצרה לרכב של מותג",
    peer_to_peer_carsharing: "שיתוף רכב בין פרטיים",
    corporate_campus_sharing: "שיתוף רכב ארגוני / קמפוס"
  }
};

window.CITY_TRANSLATIONS = {
  "Tel Aviv": "תל אביב",
  "Tel Aviv-Yafo": "תל אביב-יפו",
  "Jerusalem": "ירושלים",
  "Haifa": "חיפה",
  "Netanya": "נתניה",
  "Herzliya": "הרצליה",
  "Petah Tikva": "פתח תקווה",
  "Modiin": "מודיעין",
  "Ramat Gan": "רמת גן",
  "Giv'atayim": "גבעתיים",
  "Kfar Saba": "כפר סבא",
  "Bat Yam": "בת ים",
  "Holon": "חולון",
  "Ra'anana": "רעננה",
  "Hod Hasharon": "הוד השרון",
  "Multiple cities in Israel": "מספר ערים בישראל",
  "50+ cities": "יותר מ-50 ערים",
  "All over the country": "ברחבי הארץ",
  "Needs city-level verification": "דורש אימות ברמת עיר",
  "Bnei Brak": "בני ברק",
  "Elad": "אלעד",
  "Beit Shemesh": "בית שמש",
  "Beitar Illit": "ביתר עילית",
  "Ashdod": "אשדוד",
  "Modiin Illit": "מודיעין עילית",
  "Meron": "מירון",
  "Rishon LeZion": "ראשון לציון",
  "Ramla": "רמלה",
  "Bat Hefer": "בת חפר",
  "Savyon": "סביון",
  "Ruppin College": "מכללת רופין",
  "Tel Aviv University": "אוניברסיטת תל אביב",
  "Afula": "עפולה",
  "Karmiel": "כרמיאל",
  "Tiberias": "טבריה",
  "Beer Sheva": "באר שבע",
  "Harish": "חריש",
  "Even Yehuda": "אבן יהודה"
};
